NoteProject.Host/Controllers/NotesController.cs
using Microsoft.AspNetCore.Mvc;
using NoteProject.Host.Base.Controllers;
using NoteProject.Host.Models;
using NoteProject.Service.Notes;

namespace NoteProject.Host.Controllers
{
    public class NotesController : BaseMvcControllers
    {
        private INoteQueryService _noteQueryService;

        public NotesController(INoteQueryService noteQueryService)
        {
            _noteQueryService = noteQueryService;
        }

        public async Task<ActionResult> Index()
        {
            var notes = await _noteQueryService.GetNotes();
            var model = NoteViewModel.FromDto(notes);
            return View(model);
        }

        [HttpGet("[controller]/{id:int}")]
        public async Task<ActionResult> Details(long id)
        {
            if (id <= 0)
                return ErrorJsonResult("Login", "Note not found");

            var note = await _noteQueryService.GetNoteById(id);
            var model = NoteViewModel.FromDto(note);
            return View(model);
        }
    }
}

NoteProject.Host/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Notes Project</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/NoteProject.Host.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="/lib/toaster/toastr.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Notes" asp-action="Index">Notes Project</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <div class="navbar-nav justify-content-between flex-grow-1">
                        <div class="">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Notes" asp-action="Index">Notes</a>
                        </div>
                        @if (!User.Identity.IsAuthenticated)
                        {
                            <div class="ml-auto me-4">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                            </div>
                        }
                        else
                        {
                            <div class="ml-auto me-4">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Notes Project 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery-ajax-validation/jquery.unobtrusive-ajax.js"></script>
    <script src="~/lib/toaster/toastr.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>